# -*- coding: utf-8 -*-
"""Logistics Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14vGiIKELOaB_VXvzdLwo91_qdTusqKlb
"""

!git init

!git config - global user.email “wahyuditaruna97@gmail.com”
!git config - global user.name “tarunawahyudi”

# Memprediksi apakah seseorang akan membeli produk setelah melihat iklan yang kita tampilkan

import pandas as pd

df = pd.read_csv('Social_Network_Ads.csv')
df.head()

df.info()

# Drop kolom yang tidak diperlukan
data = df.drop(columns=['User ID'])

# jalankan proses one-hot encoding dengan pd.get_dummies()
data = pd.get_dummies(data)
data

# pisahkan antara atribut dan label
predictions = ['Age', 'EstimatedSalary', 'Gender_Female', 'Gender_Male']
x = data[predictions]
y = data['Purchased']

# Melakukan normalisasi data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)
scaled_data = scaler.transform(x)
scaled_data = pd.DataFrame(scaled_data, columns= x.columns)
scaled_data.head()

from sklearn.model_selection import train_test_split

# kita bagi data menjadi train dan test untuk setiap atribut dan label

x_train, x_test, y_train, y_test = train_test_split(scaled_data, y, test_size=0.2, random_state=1)

from sklearn import linear_model

# latih model dengan fungsi fit

model = linear_model.LogisticRegression()
model.fit(x_train, y_train)

from sklearn.preprocessing import StandardScaler

model.score(x_test, y_test)

